Fixes

diff --git a/binstub b/binstub
--- a/binstub
+++ b/binstub
@@ -3,7 +3,7 @@ set -e
 
 status=0
 program="${0##*/}"
-PROGRAM="$(echo "$program" | tr a-z- A-Z_)"
+PROGRAM="$(echo "$program" | tr a-z-. A-Z__)"
 
 _STUB_PLAN="${PROGRAM}_STUB_PLAN"
 _STUB_RUN="${PROGRAM}_STUB_RUN"
@@ -32,16 +32,13 @@ while IFS= read -r line; do
   index=$(($index + 1))
 
   if [ -z "${!_STUB_END}" ] && [ $index -eq "${!_STUB_INDEX}" ]; then
-    # We found the plan line we're interested in.
-    # Start off by assuming success.
-    result=0
-
     # Split the line into an array of arguments to
     # match and a command to run to produce output.
-    command=" $line"
-    if [ "$command" != "${command/ : }" ]; then
-      patterns="${command%% : *}"
-      command="${command#* : }"
+    command=":"
+    patterns=" $line"
+    if [ "$patterns" != "${patterns/ : }" ]; then
+      command="${patterns#* : }"
+      patterns="${patterns%% : *}"
     fi
 
     # Naively split patterns by whitespace for now.
@@ -52,6 +49,8 @@ while IFS= read -r line; do
     set +f
     arguments=("$@")
 
+    [ ${#patterns[@]} -eq ${#arguments[@]} ]
+    result=$?
     # Match the expected argument patterns to actual
     # arguments.
     for (( i=0; i<${#patterns[@]}; i++ )); do
@@ -72,7 +71,11 @@ while IFS= read -r line; do
       status="$?"
       set -e
     else
+      #echo "Unexpected call to $program: Call $index arguments don't match." >&2
+      #echo "Expected: ${patterns[*]}" >&2
+      #echo "Actual  : ${arguments[*]}" >&2
       eval "${_STUB_RESULT}"=1
+      status=1
     fi
   fi
 done < "${!_STUB_PLAN}"
@@ -85,6 +88,7 @@ if [ -n "${!_STUB_END}" ]; then
   # If the number of lines in the plan is larger than
   # the requested index, we failed.
   if [ $index -ge "${!_STUB_INDEX}" ]; then
+    echo "$program stub plan failed.  Expected $index calls, saw $((${!_STUB_INDEX} - 1))" >&2
     eval "${_STUB_RESULT}"=1
   fi
 
@@ -95,6 +99,7 @@ else
   # If the requested index is larger than the number
   # of lines in the plan file, we failed.
   if [ "${!_STUB_INDEX}" -gt $index ]; then
+    #echo "$program stub plan failed.  Expected $((index - 1)) calls, saw ${!_STUB_INDEX}" >&2
     eval "${_STUB_RESULT}"=1
   fi
 
